linters:
  disable-all: true
  enable:
    - gofumpt
    - govet
    - gci
    - staticcheck
    - paralleltest

run:
  skip-dirs:
    - transport/simple-obfs
    - transport/clashssr
    - transport/cloudflaretls

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - prefix(github.com/sagernet/)
      - default
  staticcheck:
    go: '1.20'
